- name: Install grafana
  yum:
    name: https://dl.grafana.com/oss/release/grafana-{{ version }}-1.x86_64.rpm
    state: latest
    disable_gpg_check: yes

- name: "Grafana configuration file copy"
  template:
    src: "grafana.conf.j2"
    dest: /etc/grafana/grafana.ini
  # notify: event_restart_grafana

- name: "Grafana server started"
  service:
    name: grafana-server
    enabled: true
    state: started

- name: "Check if Grafana is accessible."
  uri:
    url: http://localhost:3000
    method: GET
    status_code: 200